# render.yaml
services:
  - type: web
    name: neurobuddy
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn neuropulse_core.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
