services:
  - type: web
    name: neurobuddy-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn neurobuddy.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: neurobuddy.settings
