# Generated by Django 5.2.3 on 2025-06-22 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodentry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='moodsuggestion',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='moodentry',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='moodsuggestion',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='moodsuggestion',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='moodsuggestion',
            name='title',
        ),
        migrations.RemoveField(
            model_name='moodsuggestion',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moodsuggestion',
            name='category',
            field=models.CharField(choices=[('quote', 'Motivational Quote'), ('video', 'Calming Video'), ('tip', 'Wellness Tip')], max_length=20),
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='updated_at',
        ),
    ]
