# Generated by Django 5.2.3 on 2025-06-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0003_alter_moodentry_options_alter_moodsuggestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='ai_insight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
