# Generated by Django 5.2.3 on 2025-06-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0004_moodentry_ai_insight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='sentiment',
            field=models.CharField(blank=True, null=True),
        ),
    ]
