# Generated by Django 5.2.3 on 2025-06-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0007_moodprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodsuggestion',
            name='source',
            field=models.CharField(default='AI', max_length=50),
        ),
        migrations.AlterField(
            model_name='moodsuggestion',
            name='category',
            field=models.CharField(choices=[('quote', 'Motivational Quote'), ('tip', 'Wellness Tip'), ('video', 'Calming Video')], max_length=20),
        ),
    ]
