# Generated by Django 5.2.3 on 2025-06-27 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0008_moodsuggestion_source_alter_moodsuggestion_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moodsuggestion',
            name='mood',
            field=models.CharField(default='neutral', max_length=50),
        ),
        migrations.AddField(
            model_name='moodsuggestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
