# Generated by Django 5.2.3 on 2025-06-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0009_moodsuggestion_mood_moodsuggestion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodsuggestion',
            name='mood',
        ),
        migrations.AddField(
            model_name='moodsuggestion',
            name='target_mood_score',
            field=models.IntegerField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')], null=True),
        ),
    ]
