# Generated by Django 5.2.3 on 2025-06-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0010_remove_moodsuggestion_mood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodsuggestion',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moodsuggestion',
            name='target_mood_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
