# Generated by Django 5.2.3 on 2025-06-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0011_alter_moodsuggestion_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodsuggestion',
            name='target_mood_score',
        ),
        migrations.RemoveField(
            model_name='moodsuggestion',
            name='user',
        ),
    ]
