# Generated by Django 5.2.3 on 2025-06-26 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('mood', '0008_moodsuggestion_source_alter_moodsuggestion_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestionfeedback',
            old_name='submitted_at',
            new_name='timestamp',
        ),
        migrations.AlterUniqueTogether(
            name='suggestionfeedback',
            unique_together={('user', 'suggestion')},
        ),
        migrations.AddField(
            model_name='suggestionfeedback',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='suggestionfeedback',
            name='feedback',
        ),
    ]
