# Generated by Django 5.2.3 on 2025-06-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_submitted_at_suggestionfeedback_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestionfeedback',
            name='liked',
        ),
        migrations.AddField(
            model_name='suggestionfeedback',
            name='feedback',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='like', max_length=10),
        ),
    ]
