# Generated by Django 5.2.3 on 2025-06-24 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_emergency_contact_email_and_more'),
        ('mood', '0007_moodprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mood.moodsuggestion'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_suggestion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
