# Generated by Django 5.2.3 on 2025-07-10 17:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0002_remove_entertainmentvideo_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainmentvideo',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
