# Generated by Django 5.2.3 on 2025-07-11 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0003_alter_entertainmentvideo_share_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainmentvideo',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entertainmentvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='video_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='entertainmentvideo',
            name='video_file',
            field=models.FileField(max_length=255, upload_to='entertainment_videos/'),
        ),
    ]
