# Generated by Django 5.2.3 on 2025-07-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0004_entertainmentvideo_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainmentvideo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
