# Generated by Django 5.2.3 on 2025-07-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0005_entertainmentvideo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
