# Generated by Django 5.2.3 on 2025-07-14 12:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0006_videocomment_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainmentvideo',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='entertainmentvideo',
            name='video_file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
