# Generated by Django 5.2.3 on 2025-07-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0007_alter_entertainmentvideo_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainmentvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='video_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='entertainmentvideo',
            name='video_file',
            field=models.FileField(max_length=255, upload_to='entertainment_videos/'),
        ),
    ]
