# Generated by Django 5.2.3 on 2025-07-18 11:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0008_alter_entertainmentvideo_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainmentvideo',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='entertainmentvideo',
            name='video_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
