# Generated by Django 5.2.3 on 2025-07-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0009_alter_entertainmentvideo_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainmentvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/'),
        ),
    ]
