# Generated by Django 5.2.3 on 2025-08-05 13:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0010_alter_entertainmentvideo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainmentvideo',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
